Repository aws-solutions/aws-media-insights-engine, pull requests merged in 2021-03, with the labels that each got.

#392 fix bug introduced by pr #391
  .github/workflows/scheduled-workflow.yml
  test/e2e/conftest.py
Labels: bug, bug: minor

#388 Anonymous data collection
  .github/workflows/pr-workflow.yml
  .github/workflows/release-workflow.yml
  .github/workflows/scheduled-workflow.yml
  README.md
  deployment/build-s3-dist.sh
  deployment/media-insights-stack.yaml
  source/anonymous-data-logger/anonymous-data-logger.py
  source/anonymous-data-logger/lib/cfnresponse.py
  source/anonymous-data-logger/lib/metrics.py
  source/anonymous-data-logger/requirements.txt
Labels: type: solution builder

#402 fix operator timeouts
  source/operators/operator-library.yaml
Labels: point: 1
